CONFIG_PMW3610=y
CONFIG_PMW3610_INVERT_X=y
CONFIG_PMW3610_INVERT_Y=n
CONFIG_PMW3610_ORIENTATION_90=y
CONFIG_INPUT=y
CONFIG_PMW3610_AUTOMOUSE_TIMEOUT_MS=500
CONFIG_PMW3610_SCROLL_TICK=16
CONFIG_PMW3610_INVERT_SCROLL_X=y
CONFIG_PMW3610_INVERT_SCROLL_Y=n
CONFIG_PMW3610_SMART_ALGORITHM=y
